[package]
name = "axum-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.17"
hyper = "0.14.20"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
