[package]
name = "cmp-std-rayon-tokio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6.1"
tokio = { version = "1.23.0", features = ["full"] }
